#! /usr/bin/env bash
echo Creating virtual env...
python3 -m venv .venv
echo Installing dependencies...
.venv/bin/python3 -m pip install -r ./requirements.txt -q
.venv/bin/antlr4 -o runtime -Dlanguage=Python3 Sugarc.g4
echo Compiling...
.venv/bin/python3 main.py teste.sugarc
